03 mongodb
Mariana-Diachun/nodejs-homework-rest-api pull request #2
Opened 2023-01-13 15:24 UTC by Mariana-Diachun

2023-01-15 13:49 UTC, KhYulian requested changes
Потрібне доопрацювання

2023-01-15 13:49 UTC, KhYulian commented on app.js
> +
видаліть пусту строку після res

2023-01-15 13:49 UTC, KhYulian commented on controllers/contacts.controllers.js
>  async function getContactsService(req, res) {
У сервіси не потрібно передавати req, res, next. Вони просто роблять запит в бд і повертають результат, і відповідь відправляю контроллер. try catch в сервісах можете видалити, а помилки обробляти в контроллері

2023-01-15 13:49 UTC, KhYulian commented on server.js
> +(async function main() {
імя функції давати не потрібно в цьому випадку

2023-01-15 13:49 UTC, KhYulian commented on routes/contacts.js
> +);
для patch, post, put запитів додайте валідацію полів. Використовуйте Joi та окрему middleware, яка спрацьовувати перед кнтроллером

2023-01-15 14:13 UTC, Mariana-Diachun commented on server.js
> +(async function main() {
fixed

2023-01-15 16:03 UTC, Mariana-Diachun commented on routes/contacts.js
> +);
fixed

2023-01-15 16:14 UTC, Mariana-Diachun commented on controllers/contacts.controllers.js
>  async function getContactsService(req, res) {
Винесла сервіси окремими функціями, переробила контроллери, але метод put, patch, post поламались і я не розумію як виправити. Зможете наштовхнути ?

2023-01-15 20:30 UTC, Mariana-Diachun commented on app.js
> +
fixed

2023-01-16 10:01 UTC, Mariana-Diachun commented on controllers/contacts.controllers.js
>  async function getContactsService(req, res) {
Все пофіксила, все працює.

2023-01-16 10:40 UTC, KhYulian approved these changes
Чудова робота ❤️❤️

2023-01-16 10:40 UTC, merged