Hw05 avatars
Mariana-Diachun/nodejs-homework-rest-api pull request #4
Opened 2023-01-31 18:30 UTC by Mariana-Diachun

2023-01-31 19:17 UTC, KhYulian requested changes
Потрібні правки

2023-01-31 19:17 UTC, KhYulian commented on controllers/auth.controller.js
>  const userService = require("../services/userService");
Можна зробити деструктуризацію

2023-01-31 21:36 UTC, Mariana-Diachun commented on controllers/auth.controller.js
>  const userService = require("../services/userService");
fixed

2023-01-31 21:37 UTC, Mariana-Diachun commented
all the bugs are fixed

2023-02-01 07:46 UTC, KhYulian approved these changes
Чудова робота :)

2023-02-01 07:46 UTC, merged